### PR TITLE
Create hadley.html

### PR DESCRIPTION
**Pull request by L-Hadley**
Updated version:

[hadley.html.zip](https://github.com/chicas-lancaster/websource/files/7928789/hadley.html.zip)

### CODE REVIEW

**Comment by barryrowlingson** [comment]
Hi! Am I right to think that the actual commits in this PR are superseded by the contents of the zip file linked in the first comment? If so I'll merge it all manually.

Just for clarity, "Hadley" is the surname you use now, and "newbury" is your university username? Not a problem, just want to make sure everything is correct.

Finally, we use "status: pdra" for research staff on fixed-term contracts, and "staff" for academic staff on indefinite ("permanent") contracts, so I'll change that for you as well.

Thanks for the updates!

**Comment by L-Hadley** [comment]
> Hi! Am I right to think that the actual commits in this PR are superseded by the contents of the zip file linked in the first comment? If so I'll merge it all manually.

Hello! Yes, apologies I realised I hadn't edited the website section in the first version. The file in the zip folder is correct.


> Just for clarity, "Hadley" is the surname you use now, and "newbury" is your university username? Not a problem, just want to make sure everything is correct.

Yes, it is my married (and current) name but I was Newbury when I joined Lancaster, hence the different username. Incidentally, I will be returning to my maiden name in the near future so unfortunately I will need to update all this again when that goes through.

> Finally, we use "status: pdra" for research staff on fixed-term contracts, and "staff" for academic staff on indefinite ("permanent") contracts, so I'll change that for you as well.

No problem, thanks for spotting this! Let me know if I need to do anything further.

**Comment by barryrowlingson** [comment]
That's now live - let me know any changes via new github PRs or issues.

**Comment by L-Hadley** [comment]
Great, thanks. Will do :)

**Pull request merged**
